# Exploratory Data Analysis like

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os
import pathlib

data_path = pathlib.Path.home() / ".cache" / "kagglehub" / "competitions" / "titanic"
train_path = os.path.join(data_path, "train.csv")
test_path = os.path.join(data_path, "test.csv")

In [ ]:
df = pd.read_csv(train_path)
df.dropna(inplace=True)

df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S

In [ ]:
df = df.drop(["Name", "Cabin", "Embarked", "Ticket", "Fare", "PassengerId"], axis=1)

In [ ]:
df.head()

    Survived  Pclass     Sex   Age  SibSp  Parch
1          1       1  female  38.0      1      0
3          1       1  female  35.0      1      0
6          0       1    male  54.0      0      0
10         1       3  female   4.0      1      1
11         1       1  female  58.0      0      0

In [ ]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

le.fit(df.Sex)

le.classes_

df.Sex = le.transform(df.Sex)

In [ ]:
df.head()

    Survived  Pclass  Sex   Age  SibSp  Parch
1          1       1    0  38.0      1      0
3          1       1    0  35.0      1      0
6          0       1    1  54.0      0      0
10         1       3    0   4.0      1      1
11         1       1    0  58.0      0      0

In [ ]:
Y = df.Survived.to_numpy()
X = df.drop("Survived", axis=1).to_numpy()